\i 04_TIPOS/01_GENERAL/TYPE_TO_AU_ROL.sql

\i 04_TIPOS/01_GENERAL/TYPE_TO_AU_USUARIO.sql

\i 04_TIPOS/01_GENERAL/TYPE_TO_GE_DEPTO.sql

\i 04_TIPOS/01_GENERAL/TYPE_TO_GE_ERRO.sql

\i 04_TIPOS/01_GENERAL/TYPE_TO_GE_LGTR.sql

\i 04_TIPOS/01_GENERAL/TYPE_TO_GE_MENU.sql

\i 04_TIPOS/01_GENERAL/TYPE_TO_GE_MNSJE.sql

\i 04_TIPOS/01_GENERAL/TYPE_TO_GE_MODULO.sql

\i 04_TIPOS/01_GENERAL/TYPE_TO_GE_PAIS.sql

\i 04_TIPOS/01_GENERAL/TYPE_TO_GE_SRVCIO.sql

\i 04_TIPOS/01_GENERAL/TYPE_TO_GE_CIUD.sql

\i 04_TIPOS/01_GENERAL/TYPE_TO_GE_TPDOC.sql

\i 04_TIPOS/01_GENERAL/TYPE_TO_GE_TPER.sql

\i 04_TIPOS/01_GENERAL/TYPE_TO_AU_TOKEN.sql

\i 04_TIPOS/01_GENERAL/TYPE_TO_AU_LOGINI.sql

\i 04_TIPOS/01_GENERAL/TYPE_TO_AU_TPERSN.sql

\i 04_TIPOS/01_GENERAL/TYPE_TT_AU_ROL.sql

\i 04_TIPOS/01_GENERAL/TYPE_TT_AU_USUARIO.sql

\i 04_TIPOS/01_GENERAL/TYPE_TT_GE_DEPTO.sql

\i 04_TIPOS/01_GENERAL/TYPE_TT_GE_ERRO.sql

\i 04_TIPOS/01_GENERAL/TYPE_TT_GE_LGTR.sql

\i 04_TIPOS/01_GENERAL/TYPE_TT_GE_MENU.sql

\i 04_TIPOS/01_GENERAL/TYPE_TT_GE_MNSJE.sql

\i 04_TIPOS/01_GENERAL/TYPE_TT_GE_MODULO.sql

\i 04_TIPOS/01_GENERAL/TYPE_TT_GE_PAIS.sql

\i 04_TIPOS/01_GENERAL/TYPE_TT_GE_SRVCIO.sql

\i 04_TIPOS/01_GENERAL/TYPE_TT_GE_CIUD.sql

\i 04_TIPOS/01_GENERAL/TYPE_TT_GE_TPDOC.sql

\i 04_TIPOS/01_GENERAL/TYPE_TT_GE_TPER.sql

\i 04_TIPOS/01_GENERAL/TYPE_TT_AU_TOKEN.sql

\i 04_TIPOS/01_GENERAL/TYPE_TT_AU_LOGINI.sql

\i 04_TIPOS/01_GENERAL/TYPE_TT_AU_TPERSN.sql
