Insert into ow_base_us.AUT_TSERVC (SERVICIO_SERVICIO,SERVICIO_MODULO,SERVICIO_DESCRI,SERVICIO_NOMB,SERVICIO_TIPO,SERVICIO_ORDEN) values ('1','GEN','Inicio de sesión','Inicio de sesión','O','10');
Insert into ow_base_us.AUT_TSERVC (SERVICIO_SERVICIO,SERVICIO_MODULO,SERVICIO_DESCRI,SERVICIO_NOMB,SERVICIO_TIPO,SERVICIO_ORDEN) values ('50','GEN','DashBoard','DashBoard','O','20');
--
Insert into ow_base_us.AUT_TSERVC (SERVICIO_SERVICIO,SERVICIO_MODULO,SERVICIO_DESCRI,SERVICIO_NOMB,SERVICIO_TIPO,SERVICIO_ORDEN) values ('100','ADM','Registrar Usuarios del Sistema','Registro','O','1');
Insert into ow_base_us.AUT_TSERVC (SERVICIO_SERVICIO,SERVICIO_MODULO,SERVICIO_DESCRI,SERVICIO_NOMB,SERVICIO_TIPO,SERVICIO_ORDEN) values ('120','ADM','Consultar Usuarios del Sistema','Consulta','O','20');
Insert into ow_base_us.AUT_TSERVC (SERVICIO_SERVICIO,SERVICIO_MODULO,SERVICIO_DESCRI,SERVICIO_NOMB,SERVICIO_TIPO,SERVICIO_ORDEN) values ('140','ADM','Roles y Permisos','Roles y Permisos','O','40');
--
Insert into ow_base_us.AUT_TSERVC (SERVICIO_SERVICIO,SERVICIO_MODULO,SERVICIO_DESCRI,SERVICIO_NOMB,SERVICIO_TIPO,SERVICIO_ORDEN) values ('200','ADM','Gestionar el Perfil del Usuario actual','Mi Perfil','O','1');
Insert into ow_base_us.AUT_TSERVC (SERVICIO_SERVICIO,SERVICIO_MODULO,SERVICIO_DESCRI,SERVICIO_NOMB,SERVICIO_TIPO,SERVICIO_ORDEN) values ('220','ADM','Cambiar Contraseña','Cambiar Contraseña','O','20');
Insert into ow_base_us.AUT_TSERVC (SERVICIO_SERVICIO,SERVICIO_MODULO,SERVICIO_DESCRI,SERVICIO_NOMB,SERVICIO_TIPO,SERVICIO_ORDEN) values ('240','ADM','Parametrización General del Sistema','General','O','40');
--
Insert into ow_base_us.AUT_TSERVC (SERVICIO_SERVICIO,SERVICIO_MODULO,SERVICIO_DESCRI,SERVICIO_NOMB,SERVICIO_TIPO,SERVICIO_ORDEN) values ('99','GEN','Servicios REST','Servicios REST','O','99');
