-- INSERTING into ow_base_us.AUT_TUSUARIO
Insert into ow_base_us.AUT_TUSUARIO (USUARIO_USUARIO,USUARIO_PERSN,USUARIO_CLAVE,USUARIO_MEDIO_TOK,USUARIO_TIPO_AUT,USUARIO_USRCRE,USUARIO_FECCRE,USUARIO_ESTADO,USUARIO_AVATAR) values ('administrador','0','DQDQDqAyCoBkBhCSBcDaCNDTAcCHCRCq','M','C','administrador',to_date('23/01/18','DD/MM/RR'),'ACT','usuario-default.png');
