-- INSERTING into ow_base_us.GE_TCRTA
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('ERR_CLNTE_EXISTENTE','API_ADM_QUSUARIO.crearInfoBasicaCliente','500','El usuario ya se encuentra creado','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('COD_EXITOSO','API_ADM_QUSUARIO.crearInfoBasicaCliente','200','Operacion Exitosa','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('COD_EXITOSO','API_ow_base_us.AUT_QUSUARIO.actualizarClaveUsuario','200','Operacion Exitosa','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('ERR_WHEN_OTHERS','API_ow_base_us.AUT_QUSUARIO.actualizarClaveUsuario','500','Error no controlado','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('ERR_ROL_USUA_DUPL','API_ow_base_us.AUT_QUSUARIO.asignarRolPorUsuario','500','El usuario ya tiene asignado el rol','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('COD_EXITOSO','API_ow_base_us.AUT_QUSUARIO.asignarRolPorUsuario','200','Operacion Exitosa','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('ERR_WHEN_OTHERS','API_ow_base_us.AUT_QUSUARIO.asignarRolPorUsuario','500','Error no controlado','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('ERR_WHEN_OTHERS','API_ow_base_us.AUT_QUSUARIO.crearUsuario','500','Error no controlado','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('COD_EXITOSO','API_ow_base_us.AUT_QUSUARIO.crearUsuario','200','Operacion Exitosa','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('COD_EXITOSO','API_ow_base_us.AUT_QUSUARIO.eliminarRolesPorUsuario','200','Operacion Exitosa','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('ERR_WHEN_OTHERS','API_ow_base_us.AUT_QUSUARIO.eliminarRolesPorUsuario','500','Error no controlado','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('COD_EXITOSO','API_ow_base_us.AUT_QUSUARIO.obtenerPersona','200','Operacion Exitosa','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('ERR_WHEN_OTHERS','API_ow_base_us.AUT_QUSUARIO.obtenerPersona','500','Error no controlado','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('ERR_WHEN_OTHERS','API_ow_base_us.AUT_QUSUARIO.obtenerPersonaAsociadaUsuario','500','Error no controlado','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('COD_EXITOSO','API_ow_base_us.AUT_QUSUARIO.obtenerPersonaAsociadaUsuario','200','Operacion Exitosa','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('ERR_WHEN_OTHERS','API_ow_base_us.AUT_QUSUARIO.obtenerRolesPorUsuario','500','Error no controlado','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('COD_EXITOSO','API_ow_base_us.AUT_QUSUARIO.obtenerRolesPorUsuario','200','Operacion Exitosa','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('ERR_WHEN_OTHERS','API_ow_base_us.AUT_QUSUARIO.obtenerUsuario','500','Error no controlado','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('COD_EXITOSO','API_ow_base_us.AUT_QUSUARIO.obtenerUsuario','200','Operacion Exitosa','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('COD_EXITOSO','API_ow_base_us.GE_QMENU.modulosPorUsuario','200','Operacion Exitosa','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('ERR_WHEN_OTHERS','API_ow_base_us.GE_QMENU.modulosPorUsuario','500','Error no controlado','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('COD_EXITOSO','API_ow_base_us.GE_QMENU.obtenerMenuPorUsuario','200','Operacion Exitosa','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('ERR_WHEN_OTHERS','API_ow_base_us.GE_QMENU.obtenerMenuPorUsuario','500','Error no controlado','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('COD_EXITOSO','API_ow_base_us.GE_QMENU.paginaInicioPorUsuario','200','Operacion Exitosa','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('ERR_WHEN_OTHERS','API_ow_base_us.GE_QMENU.paginaInicioPorUsuario','500','Error no controlado','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('COD_EXITOSO','API_ow_base_us.GE_QMENU.serviciosTpListadoPorUsuario','200','Operacion Exitosa','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('ERR_WHEN_OTHERS','API_ow_base_us.GE_QMENU.serviciosTpListadoPorUsuario','500','Error no controlado','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('CAMPO_OBLIGATORIO','API_ADM_QUSUARIO.crearInfoBasicaCliente','500','La información es obligatoria para el campo','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('ERR_WHEN_OTHERS','API_ow_base_us.GE_QMENU.serviciosUsuarioPorUrl','500','Error no controlado','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('COD_EXITOSO','API_ow_base_us.GE_QMENU.serviciosUsuarioPorUrl','200','Operacion Exitosa','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('COD_EXITOSO','API_ow_base_us.GE_QMENU.titulosMenuPorUsuario','200','Operacion Exitosa','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('ERR_WHEN_OTHERS','API_ow_base_us.GE_QMENU.titulosMenuPorUsuario','500','Error no controlado','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('COD_EXITOSO','API_ow_base_us.AUT_QUSUARIO.obtenerAliadoPorUsuario','200','Operacion Exitosa','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('ERR_WHEN_OTHERS','API_ow_base_us.AUT_QUSUARIO.obtenerAliadoPorUsuario','500','Error no controlado','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('COD_EXITOSO','API_ow_base_us.AUT_QUSUARIO.generarToken','200','Operacion Exitosa','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('ERR_WHEN_OTHERS','API_ow_base_us.AUT_QUSUARIO.generarToken','500','Error no controlado','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('COD_EXITOSO','API_ow_base_us.AUT_QUSUARIO.obtenerUsuarioToken','200','Operacion Exitosa','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('ERR_WHEN_OTHERS','API_ow_base_us.AUT_QUSUARIO.obtenerUsuarioToken','500','Error no controlado','es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('COD_EXITOSO', 'API_SG_QPRESTAMO.crearInfoPrestamo', '200', 'Operacion Exitosa', 'es_CO');
Insert into ow_base_us.GE_TCRTA (CRTA_CRTA,CRTA_PRCS,CRTA_HTTP_CODE,CRTA_DESCRI,CRTA_IDIOMA) values ('ERR_WHEN_OTHERS', 'API_SG_QPRESTAMO.crearInfoPrestamo', '500', 'Error no controlado', 'es_CO');

