REM ******************************************************************
REM Fecha         : 08/05/2018
REM Realizado por : Master Zen
REM Base de Datos : FS_AUWEB_US
REM ******************************************************************

REM TABLESPACE Y SEGMENTOS DE ROLLBACK
set feedback off
spool TMP.lst

spool off
start TMP.lst
set feedback on



	DROP TABLE   "FS_AUWEB_US"."MO_TMODU" CASCADE CONSTRAINTS;



	DROP TABLE   "FS_AUWEB_US"."MO_TROMO" CASCADE CONSTRAINTS;



	DROP TABLE   "FS_AUWEB_US"."US_TPSNA" CASCADE CONSTRAINTS;



	DROP TABLE   "FS_AUWEB_US"."US_TPUSR" CASCADE CONSTRAINTS;



	DROP TABLE   "FS_AUWEB_US"."US_TROLL" CASCADE CONSTRAINTS;



	DROP TABLE   "FS_AUWEB_US"."US_TUSER" CASCADE CONSTRAINTS;
	

	
    DROP TABLE   "FS_AUWEB_US"."NE_TCRTA" CASCADE CONSTRAINTS;
	
    
 DROP SEQUENCE "FS_AUWEB_US"."MO_SMODU";
  DROP SEQUENCE "FS_AUWEB_US"."MO_SROMO";
   DROP SEQUENCE "FS_AUWEB_US"."US_SPSNA";
    DROP SEQUENCE "FS_AUWEB_US"."US_SPUSR";
     DROP SEQUENCE "FS_AUWEB_US"."US_SROLL";
      DROP SEQUENCE "FS_AUWEB_US"."US_SUSER";
	  
          
          
          
    
REM USUARIO  DUENHO DEL APLICATIVO FS_AUWEB_US
drop user FS_AUWEB_US cascade;

REM TABLESPACE DE DATOS
DROP TABLESPACE TS_TAUWEB   INCLUDING CONTENTS AND DATAFILES
    CASCADE CONSTRAINTS;


REM TABLESPACE DE INDICES 
DROP TABLESPACE TS_AUWEB INCLUDING CONTENTS AND DATAFILES
    CASCADE CONSTRAINTS;
	

REM TABLESPACE TEMPORAL
DROP tablespace TS_IAUWEB INCLUDING CONTENTS AND DATAFILES
    CASCADE CONSTRAINTS;







