/* ---------------------------------------------------- */
/*  SU GARANTIA PERSONAL - ADA                         */
/* ---------------------------------------------------- */

\i 02_TABLAS/02_AUTENTICACION/AUT_TUSUARIO.sql

\i 02_TABLAS/02_AUTENTICACION/AUT_TMENU.sql

\i 02_TABLAS/02_AUTENTICACION/AUT_TMNSRV.sql

\i 02_TABLAS/02_AUTENTICACION/AUT_TMODUL.sql

\i 02_TABLAS/02_AUTENTICACION/AUT_TROL.sql

\i 02_TABLAS/02_AUTENTICACION/AUT_TRSIN.sql

\i 02_TABLAS/02_AUTENTICACION/AUT_TSERVC.sql

\i 02_TABLAS/02_AUTENTICACION/AUT_TSROL.sql

\i 02_TABLAS/02_AUTENTICACION/AUT_TSURL.sql

\i 02_TABLAS/02_AUTENTICACION/AUT_TUROL.sql

\i 02_TABLAS/02_AUTENTICACION/AUT_TTOKEN.sql

\i 02_TABLAS/02_AUTENTICACION/AUT_TINLOG.sql

\i 02_TABLAS/02_AUTENTICACION/AUT_TPERSN.sql



