\i 05_FUNCIONES/01_GENERAL/add_days.sql
\i 05_FUNCIONES/01_GENERAL/dias.sql
\i 05_FUNCIONES/01_GENERAL/nextvalue.sql
\i 05_FUNCIONES/01_GENERAL/nada.sql
\i 05_FUNCIONES/01_GENERAL/tokencod.sql
\i 05_FUNCIONES/01_GENERAL/api_ge_qmenu$modulosporusuario.sql
\i 05_FUNCIONES/01_GENERAL/api_ge_qmenu$obtenermenuporusuario.sql
\i 05_FUNCIONES/01_GENERAL/api_ge_qmenu$paginainicioporusuario.sql
\i 05_FUNCIONES/01_GENERAL/api_ge_qmenu$serviciostplistadoporusuario.sql
\i 05_FUNCIONES/01_GENERAL/api_ge_qmenu$serviciosusuarioporurl.sql
\i 05_FUNCIONES/01_GENERAL/api_ge_qmenu$titulosmenuporusuario.sql
\i 05_FUNCIONES/01_GENERAL/api_ge_qparametros$obtenerciuddeppais.sql
\i 05_FUNCIONES/01_GENERAL/api_ge_qparametros$obtenerlistaciudades.sql
\i 05_FUNCIONES/01_GENERAL/api_ge_qparametros$obtenerlistadeptos.sql
\i 05_FUNCIONES/01_GENERAL/api_ge_qparametros$obtenerlistapaises.sql
\i 05_FUNCIONES/01_GENERAL/api_ge_qparametros$obtenerlistatipodocumentos.sql
\i 05_FUNCIONES/01_GENERAL/api_ge_qutils$crearlogtransaccion.sql
\i 05_FUNCIONES/01_GENERAL/api_ge_qutils$generartypeerrorrpta.sql
\i 05_FUNCIONES/01_GENERAL/api_ge_qutils$generartypemensajerpta.sql
\i 05_FUNCIONES/01_GENERAL/api_ge_qutils$getmensajeporcodigo.sql
\i 05_FUNCIONES/01_GENERAL/api_ge_qutils$getnextvalue.sql
\i 05_FUNCIONES/01_GENERAL/api_ge_qutils$obtener_errores_log.sql
\i 05_FUNCIONES/01_GENERAL/api_ge_qutils$obtenerdescripcionproceso.sql
\i 05_FUNCIONES/01_GENERAL/api_ge_qutils$obtenerfechaconformato.sql
\i 05_FUNCIONES/01_GENERAL/api_ge_qutils$registrar_error.sql
\i 05_FUNCIONES/01_GENERAL/ge_qcrta$consultar_crta.sql
\i 05_FUNCIONES/01_GENERAL/ge_qlgtr$finalizar_log.sql
\i 05_FUNCIONES/01_GENERAL/ge_qlgtr$iniciar_log.sql
\i 05_FUNCIONES/01_GENERAL/ge_qlgtr$registrar_detalle_log.sql
\i 05_FUNCIONES/01_GENERAL/ge_qlgtr$validar_ctrl_operacion.sql
\i 05_FUNCIONES/01_GENERAL/ge_qmenu$modulosporusuario.sql
\i 05_FUNCIONES/01_GENERAL/ge_qmenu$obtenermenuporusuario.sql
\i 05_FUNCIONES/01_GENERAL/ge_qmenu$paginainicioporusuario.sql
\i 05_FUNCIONES/01_GENERAL/ge_qmenu$serviciostplistadoporusuario.sql
\i 05_FUNCIONES/01_GENERAL/ge_qmenu$serviciosusuarioporurl.sql
\i 05_FUNCIONES/01_GENERAL/ge_qmenu$titulosmenuporusuario.sql