\i 03_FOREIGN_KEY/02_AUTENTICACION/AUT_TMNSRV_FK.sql

\i 03_FOREIGN_KEY/02_AUTENTICACION/AUT_TRSIN_FK.sql

\i 03_FOREIGN_KEY/02_AUTENTICACION/AUT_TSERVC_FK.sql

\i 03_FOREIGN_KEY/02_AUTENTICACION/AUT_TSROL_FK.sql

\i 03_FOREIGN_KEY/02_AUTENTICACION/AUT_TSURL_FK.sql

\i 03_FOREIGN_KEY/02_AUTENTICACION/AUT_TTOKEN.sql

\i 03_FOREIGN_KEY/02_AUTENTICACION/AUT_TUROL_FK.sql

\i 03_FOREIGN_KEY/02_AUTENTICACION/AUT_TUSUARIO_FK.sql

\i 03_FOREIGN_KEY/02_AUTENTICACION/AUT_TPERSN_FK.sql

