-- INSTALL OBJECTS...

\i 01_SECUENCIAS/INSTALL_SECUENCIAS.sql
\i 02_TABLAS/INSTALL_TABLAS.sql
\i 03_FOREIGN_KEY/INSTALL_FOREIGN.sql
\i 04_TIPOS/INSTALL_TIPOS.sql
\i 05_FUNCIONES/INSTALL_FUNCIONES.sql
\i 06_DATOS/INSTALL_DATOS.sql

